# Generated by Django 3.0.6 on 2020-05-25 06:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ICD-Code')),
                ('name', models.TextField(unique=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='ATC-Code')),
                ('name', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateField(verbose_name='Beginning of illness')),
                ('severity', models.IntegerField(choices=[(1, 'mild'), (2, 'moderate'), (3, 'severe')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Beginning of medication')),
                ('dosage', models.PositiveIntegerField()),
                ('dosage_unit', models.PositiveIntegerField(choices=[(1, 'milligram'), (2, 'gram')])),
                ('dosage_form', models.PositiveIntegerField(choices=[(1, 'Oral'), (2, 'Ophthalmic'), (3, 'Inhalation'), (4, 'Parenteral'), (5, 'Topical'), (6, 'Suppository')])),
                ('count', models.PositiveIntegerField(verbose_name='Dosage quantity')),
                ('time_unit', models.PositiveIntegerField(choices=[(1, 'day'), (2, 'week')], verbose_name='per')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identifer', models.CharField(max_length=10, verbose_name='Patient ID')),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')])),
                ('birth_year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)], verbose_name='Year of birth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
