# Generated by Django 3.0.6 on 2020-05-25 07:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200525_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreexistingIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateField(verbose_name='Beginning of illness')),
                ('severity', models.IntegerField(choices=[(1, 'mild'), (2, 'moderate'), (3, 'severe')])),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Illness',
        ),
    ]
