# Generated by Django 3.0.6 on 2020-05-25 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_covidillness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidillness',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.Patient'),
        ),
    ]
