# Generated by Django 3.0.6 on 2020-05-25 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200525_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidillness',
            name='severity',
        ),
        migrations.AddField(
            model_name='covidillness',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End of symptoms'),
        ),
        migrations.AddField(
            model_name='covidillness',
            name='mild',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covidillness',
            name='moderate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covidillness',
            name='severe',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='covidillness',
            name='symptom_free',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='covidillness',
            name='start',
            field=models.DateField(verbose_name='Start of symptoms'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='start',
            field=models.DateField(verbose_name='Start of medication'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)], verbose_name='Year of birth'),
        ),
        migrations.AlterField(
            model_name='preexistingillness',
            name='severity',
            field=models.IntegerField(choices=[(1, 'no symptoms'), (2, 'mild'), (3, 'moderate'), (4, 'severe')]),
        ),
        migrations.AlterField(
            model_name='preexistingillness',
            name='start',
            field=models.DateField(verbose_name='Start of symptoms'),
        ),
    ]
