# Generated by Django 3.0.6 on 2020-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200525_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidillness',
            name='mild',
        ),
        migrations.RemoveField(
            model_name='covidillness',
            name='moderate',
        ),
        migrations.RemoveField(
            model_name='covidillness',
            name='severe',
        ),
        migrations.RemoveField(
            model_name='covidillness',
            name='symptom_free',
        ),
        migrations.AddField(
            model_name='covidillness',
            name='days_mild',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Days mild'),
        ),
        migrations.AddField(
            model_name='covidillness',
            name='days_moderate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Days moderate'),
        ),
        migrations.AddField(
            model_name='covidillness',
            name='days_severe',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Days severe'),
        ),
        migrations.AddField(
            model_name='covidillness',
            name='days_symptom_free',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Days symptom free'),
        ),
        migrations.AddField(
            model_name='medication',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End of medication'),
        ),
    ]
