# Generated by Django 3.0.6 on 2020-05-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20200525_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start of medication')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End of medication')),
                ('dosage', models.PositiveIntegerField()),
                ('dosage_unit', models.PositiveIntegerField(choices=[(1, 'milligram'), (2, 'gram')])),
                ('dosage_form', models.PositiveIntegerField(choices=[(1, 'Oral'), (2, 'Ophthalmic'), (3, 'Inhalation'), (4, 'Parenteral'), (5, 'Topical'), (6, 'Suppository')])),
                ('count', models.PositiveIntegerField(verbose_name='Quantity')),
                ('time_unit', models.PositiveIntegerField(choices=[(1, 'day'), (2, 'week')], verbose_name='per')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreexistingMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start of medication')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End of medication')),
                ('dosage', models.PositiveIntegerField()),
                ('dosage_unit', models.PositiveIntegerField(choices=[(1, 'milligram'), (2, 'gram')])),
                ('dosage_form', models.PositiveIntegerField(choices=[(1, 'Oral'), (2, 'Ophthalmic'), (3, 'Inhalation'), (4, 'Parenteral'), (5, 'Topical'), (6, 'Suppository')])),
                ('count', models.PositiveIntegerField(verbose_name='Quantity')),
                ('time_unit', models.PositiveIntegerField(choices=[(1, 'day'), (2, 'week')], verbose_name='per')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Drug')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
    ]
