# Generated by Django 3.0.6 on 2020-05-25 19:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20200525_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidTherapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('therapy_form', models.PositiveSmallIntegerField(choices=[(1, 'Ventilator')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='covidmedication',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='covidmedication',
            name='dosage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='covidmedication',
            name='dosage_form',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Oral'), (2, 'Ophthalmic'), (3, 'Inhalation'), (4, 'Parenteral'), (5, 'Topical'), (6, 'Suppository')]),
        ),
        migrations.AlterField(
            model_name='covidmedication',
            name='dosage_unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'milligram'), (2, 'gram')]),
        ),
        migrations.AlterField(
            model_name='covidmedication',
            name='time_unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'day'), (2, 'week')], verbose_name='per'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)], verbose_name='Year of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Other')]),
        ),
        migrations.AlterField(
            model_name='preexistingillness',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'no symptoms'), (2, 'mild'), (3, 'moderate'), (4, 'severe')]),
        ),
        migrations.AlterField(
            model_name='preexistingmedication',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='preexistingmedication',
            name='dosage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='preexistingmedication',
            name='dosage_form',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Oral'), (2, 'Ophthalmic'), (3, 'Inhalation'), (4, 'Parenteral'), (5, 'Topical'), (6, 'Suppository')]),
        ),
        migrations.AlterField(
            model_name='preexistingmedication',
            name='dosage_unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'milligram'), (2, 'gram')]),
        ),
        migrations.AlterField(
            model_name='preexistingmedication',
            name='time_unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'day'), (2, 'week')], verbose_name='per'),
        ),
    ]
