# Generated by Django 3.0.6 on 2020-05-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20200525_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidtherapy',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Patient'),
        ),
    ]
