# Generated by Django 3.0.6 on 2020-05-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20200525_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidtherapy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Patient'),
        ),
    ]
