# Generated by Django 3.0.6 on 2020-05-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20200525_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidillness',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start of symptoms'),
        ),
    ]
