# Generated by Django 3.0.6 on 2020-05-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20200526_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidmedication',
            name='dosage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preexistingmedication',
            name='dosage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
