# Generated by Django 3.0.6 on 2020-05-26 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20200526_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidillness',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='register.Disease'),
        ),
    ]
